# Generated by Django 3.1.1 on 2020-09-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='flashcards',
            field=models.ManyToManyField(to='flashcards.Flashcard'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='decks',
            field=models.ManyToManyField(to='flashcards.Deck'),
        ),
    ]
