# Generated by Django 3.1.1 on 2020-10-01 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_auto_20200930_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='decks',
        ),
    ]
